### ISSUE TITLE
Quant Assignment 1

### ISSUE THREAD

**Issue by mggetts** [SES-5215-F2020/mgetts-quant#1]
Both the .Rmd file and the html file are ready for grading. I hope you like them. :) I look forward to your feedback.

**Comment by saratepfer** [comment]
Nice job on this assignment. You still seem to have some variables in your dataset that you don't list in step 3. For example, ST and ST_label. You may also want to rename/keep just the label versions of some of the variables you've selected. For example, you've renamed RACAIAN to AIAN in line 88, which leaves you with AIAN and RACAIAN_label in your dataset. You may instead want to rename RACAIAN_label to AIAN and drop the RCAIAN altogether. Either way, I would continue to clean up your dataset to ensure that the number of variables you have matches the number of variables you list in step 3.
