### ISSUE TITLE
Assignment 3: Late

### ISSUE THREAD

**Issue by mggetts** [SES-5215-F2020/mgetts-quant#3]
https://ses-5215-f2020.github.io/mgetts-quant/Quant3Messy.Rmd
https://ses-5215-f2020.github.io/mgetts-quant/Quant3Messy.html

**Comment by saratepfer** [comment]
Nice job, Marissa! Please note: no need to assign Catherine to this issue. Only Carole and I will be doing grading. Please see a few comments below:

- In your interpretations of the Pearson's correlations, I wouldn't say, "No linear relationship"; instead, I would probably say, "very weak linear relationship" or something similar.
- In your graphs of the correlations, you can precede the ggplot() line with the following line of code to remove the scientific notation: options(scipen = 999)
- It would be great if you could include some interpretation of the graphs you've shown, and additionally show the 95% confidence interval on each of the graphs.
- line 387/388: add an extra return here to allow the "categorical/categorical" header to be on its own line.
